import { NextRequest, NextResponse } from 'next/server'
import { Prisma } from '@prisma/client'
import { prisma } from '@/lib/db/prisma'
import { ensureOrgAccessApi } from '@/lib/auth/ensureOrgAccessApi'
import { isoToUTCDateOnly, dateToISOString } from '@/lib/dates/dateOnly'
import { fetchTrialBalanceAccounts } from '@/lib/tb/trialBalanceAccounts'

const numberOrZero = (v: any) => {
  const n = Number(v)
  return Number.isFinite(n) ? n : 0
}

const numberOrNull = (v: any) => {
  const n = Number(v)
  return Number.isFinite(n) ? n : null
}

const decimal = (v: number | null) => (v === null ? null : new Prisma.Decimal(v))

const mapSchedule = (s: any) => ({
  id: s.id,
  orgId: s.orgId,
  periodStart: dateToISOString(new Date(s.periodStart)),
  periodEnd: dateToISOString(new Date(s.periodEnd)),
  name: s.name,
  type: s.type,
  glAccountId: s.glAccountId,
  glAccountName: s.glAccountName,
  glAccountNumber: s.glAccountNumber,
  currency: s.currency,
  openingBalance: numberOrZero(s.openingBalance),
  additions: numberOrZero(s.additions),
  reductions: numberOrZero(s.reductions),
  activityExpense: numberOrZero(s.activityExpense),
  endingBalance: numberOrZero(s.endingBalance),
  tbEndingBalance: numberOrNull(s.tbEndingBalance),
  varianceToTB: numberOrNull(s.varianceToTB),
  status: s.status,
  notes: s.notes,
  preparedBy: s.preparedBy,
  preparedAt: s.preparedAt?.toISOString?.() || null,
  reviewedBy: s.reviewedBy,
  reviewedAt: s.reviewedAt?.toISOString?.() || null,
  lockAccount: !!s.lockAccount,
  lockPeriod: !!s.lockPeriod,
  amortMethod: s.amortMethod,
  amortStartDate: s.amortStartDate ? s.amortStartDate.toISOString() : null,
  amortEndDate: s.amortEndDate ? s.amortEndDate.toISOString() : null,
  amortMonthlyAmount: numberOrNull(s.amortMonthlyAmount),
  amortAutoGenerated: !!s.amortAutoGenerated,
  createdAt: s.createdAt?.toISOString?.() || null,
  updatedAt: s.updatedAt?.toISOString?.() || null,
})

const parseDateTime = (v: any): Date | null => {
  if (!v) return null
  const d = new Date(v)
  return isNaN(d.getTime()) ? null : d
}

function pickParam(searchParams: URLSearchParams, keys: string[]): string | null {
  for (const key of keys) {
    const val = searchParams.get(key)
    if (val) return val
  }
  return null
}

export async function GET(req: NextRequest) {
  try {
    if (!(prisma as any).schedule?.findMany) {
      console.error('[Schedules][GET] prisma.schedule missing — run prisma generate after migration')
      return NextResponse.json({ schedules: [], warning: 'Prisma client not updated; run prisma generate' })
    }

    const { searchParams } = new URL(req.url)
    const orgId = pickParam(searchParams, ['orgId', 'org_id'])
    const periodStart =
      pickParam(searchParams, ['periodStart', 'period_start', 'from', 'fromDate']) ||
      undefined
    const periodEnd =
      pickParam(searchParams, ['periodEnd', 'period_end', 'to', 'toDate']) || undefined

    if (!orgId || !periodStart || !periodEnd) {
      return NextResponse.json(
        { error: 'orgId, periodStart, and periodEnd are required' },
        { status: 400 },
      )
    }

    await ensureOrgAccessApi(orgId)

    const schedules = await prisma.schedule.findMany({
      where: {
        orgId,
        periodStart: isoToUTCDateOnly(periodStart),
        periodEnd: isoToUTCDateOnly(periodEnd),
        deletedAt: null,
      },
      orderBy: { updatedAt: 'desc' },
    })

    return NextResponse.json({ schedules: schedules.map(mapSchedule) })
  } catch (error: any) {
    console.error('[Schedules][GET] error', error)
    return NextResponse.json({ error: error.message || 'Failed to load schedules' }, { status: 500 })
  }
}

export async function POST(req: NextRequest) {
  try {
    if (!(prisma as any).schedule?.create) {
      return NextResponse.json(
        { error: 'Prisma client not updated; run prisma generate after migration' },
        { status: 500 },
      )
    }

    const body = await req.json()
    const orgId = body.orgId as string
    const periodStart = body.periodStart as string
    const periodEnd = body.periodEnd as string
    const name = (body.name || '').trim()
    const type = (body.type || '').toString().toUpperCase()
    const glAccountId = (body.glAccountId || '').toString()
    const glAccountNameInput = (body.glAccountName || '').toString()
    const glAccountNumberInput = body.glAccountNumber ? String(body.glAccountNumber) : null
    const currency = body.currency || 'USD'
    const notes = body.notes || null
    const lines = Array.isArray(body.lines) ? body.lines : []
    const amortMethod = (body.amortMethod || 'NONE').toString().toUpperCase()
    const amortStartDate = body.amortStartDate ? isoToUTCDateOnly(body.amortStartDate) : null
    const amortEndDate = body.amortEndDate ? isoToUTCDateOnly(body.amortEndDate) : null
    const amortMonthlyAmount = body.amortMonthlyAmount !== undefined ? numberOrZero(body.amortMonthlyAmount) : null
    const amortAutoGenerated = !!body.amortAutoGenerated

    if (!orgId || !periodStart || !periodEnd) {
      return NextResponse.json(
        { error: 'orgId, periodStart, and periodEnd are required' },
        { status: 400 },
      )
    }
    if (!name) {
      return NextResponse.json({ error: 'name is required' }, { status: 400 })
    }
    if (!glAccountId) {
      return NextResponse.json({ error: 'glAccountId is required' }, { status: 400 })
    }
    if (!['PREPAID', 'FIXED_ASSET', 'LOAN', 'OTHER'].includes(type)) {
      return NextResponse.json({ error: 'invalid schedule type' }, { status: 400 })
    }

    const startDate = isoToUTCDateOnly(periodStart)
    const endDate = isoToUTCDateOnly(periodEnd)
    if (startDate > endDate) {
      return NextResponse.json({ error: 'periodStart must be on/before periodEnd' }, { status: 400 })
    }

    await ensureOrgAccessApi(orgId)

    const openingBalance = numberOrZero(body.openingBalance)
    const additions = numberOrZero(body.additions)
    const reductions = numberOrZero(body.reductions)
    const activityExpenseInput = Math.max(0, numberOrZero(body.activityExpense))
    const adjustments = lines
      .filter((l: any) => (l.lineType || l.type || '').toString().toUpperCase() === 'ADJUSTMENT')
      .reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)

    const { accounts } = await fetchTrialBalanceAccounts(orgId, periodStart, periodEnd)
    const tbAccount =
      accounts.find((a) => a.accountId === glAccountId) ||
      accounts.find((a) => a.accountName.toLowerCase() === glAccountNameInput.toLowerCase())

    const tbEndingBalance = tbAccount ? tbAccount.ending : null
    const resolvedAccountName = glAccountNameInput || tbAccount?.accountName || ''
    const resolvedAccountNumber = glAccountNumberInput ?? tbAccount?.accountNumber ?? null

    // If lines exist, compute additions/reductions/adjustments from lines and lock manual fields
    let computedAdditions = additions
    let computedReductions = reductions
    let computedAdjustments = adjustments
    let autoAmortActivity = 0
    if (lines.length > 0) {
      computedAdditions = lines
        .filter((l: any) => (l.lineType || l.type || '').toString().toUpperCase() === 'ADDITION')
        .reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)
      computedReductions = lines
        .filter((l: any) => (l.lineType || l.type || '').toString().toUpperCase() === 'REDUCTION')
        .reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)
      const adjustmentLines = lines
        .filter((l: any) => (l.lineType || l.type || '').toString().toUpperCase() === 'ADJUSTMENT')
      computedAdjustments = adjustmentLines.reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)
      autoAmortActivity = adjustmentLines
        .filter((l: any) => l.isAutoGenerated || (l.generatedSource || '').toString().toUpperCase() === 'AMORTIZATION')
        .reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)
    }

    const endingBalance =
      openingBalance + computedAdditions - computedReductions + computedAdjustments - (activityExpenseInput + autoAmortActivity)
    const varianceToTB =
      tbEndingBalance === null || tbEndingBalance === undefined ? null : endingBalance - tbEndingBalance

    const requestedStatus = (body.status || '').toString().toUpperCase()
    const reviewedBy = body.reviewedBy ? String(body.reviewedBy) : null
    const reviewedAt = body.reviewedAt ? isoToUTCDateOnly(body.reviewedAt) : null
    const preparedAtInput = parseDateTime(body.preparedAt) || new Date()

    const statusChecks = () => {
      if (requestedStatus === 'CLOSED') {
        // Can only close if active rules satisfied and reviewed
        if (!tbEndingBalance && tbEndingBalance !== 0) return 'TB ending balance required to close'
        if (Math.abs(varianceToTB ?? 0) > 0.01) return 'Variance must be within ±0.01 to close'
        if (!reviewedBy || !reviewedAt) return 'Reviewed By and Reviewed At are required to close'
      }
      if (requestedStatus === 'ACTIVE') {
        if (!tbEndingBalance && tbEndingBalance !== 0) return 'TB ending balance required for Active'
        if (Math.abs(varianceToTB ?? 0) > 0.01) return 'Variance must be within ±0.01 for Active'
        if (!reviewedBy || !reviewedAt) return 'Reviewed By and Reviewed At required for Active'
      }
      return null
    }
    const statusError = statusChecks()
    if (statusError) {
      return NextResponse.json({ error: statusError }, { status: 400 })
    }

    const status =
      ['DRAFT', 'ACTIVE', 'CLOSED'].includes(requestedStatus) && requestedStatus ? requestedStatus : 'DRAFT'

    const created = await prisma.schedule.create({
      data: {
        orgId,
        periodStart: startDate,
        periodEnd: endDate,
        name,
        type,
        glAccountId,
        glAccountName: resolvedAccountName,
        glAccountNumber: resolvedAccountNumber,
        currency,
        openingBalance: decimal(openingBalance)!,
        additions: decimal(computedAdditions)!,
        reductions: decimal(computedReductions)!,
        activityExpense: decimal(activityExpenseInput + autoAmortActivity)!,
        endingBalance: decimal(endingBalance)!,
        tbEndingBalance: decimal(tbEndingBalance),
        varianceToTB: decimal(varianceToTB),
        status,
        notes,
        preparedBy: body.preparedBy || null,
        preparedAt: preparedAtInput,
        reviewedBy,
        reviewedAt,
        amortMethod,
        amortStartDate,
        amortEndDate,
        amortMonthlyAmount: amortMonthlyAmount !== null ? decimal(amortMonthlyAmount) : null,
        amortAutoGenerated,
      },
    })

    // Persist lines if provided
    if (lines.length > 0 && (prisma as any).scheduleLine?.createMany) {
      const lineRows = lines.map((l: any) => ({
        scheduleId: created.id,
        lineType: (l.lineType || l.type || '').toString().toUpperCase(),
        lineDate: isoToUTCDateOnly(l.lineDate || l.date || periodStart),
        description: String(l.description || '').trim() || 'Line',
        reference: l.reference ? String(l.reference) : null,
        vendor: l.vendor ? String(l.vendor) : null,
        amount: new Prisma.Decimal(numberOrZero(l.amount)),
      }))
      if (lineRows.length > 0) {
        await prisma.scheduleLine.createMany({ data: lineRows })
      }
    }

    return NextResponse.json({ schedule: mapSchedule(created) })
  } catch (error: any) {
    console.error('[Schedules][POST] error', error)
    return NextResponse.json({ error: error.message || 'Failed to create schedule' }, { status: 500 })
  }
}
