export type RuleTemplate = {
  key: string
  name: string
  description: string
  severity: 'low' | 'medium' | 'high' | 'critical'
  domain?: 'GL' | 'PROJECT_PNL'
  metric?: 'revenue' | 'cogs' | 'gross_profit' | 'gp_percent'
  scope: 'ALL' | 'ACCOUNT_MATCH'
  account_match?: string
  variance_mode?: 'NONE' | 'ABS_DELTA' | 'PCT_DELTA'
  variance_threshold?: number
  variance_basis?: 'PRIOR_MONTH' | 'PRIOR_QUARTER' | 'PRIOR_YEAR_SAME_MONTH'
  threshold_abs?: number
  threshold_pos?: number
  threshold_neg?: number
  target?: string
  rule_type?: string
}

export const RULE_TEMPLATES: RuleTemplate[] = [
  {
    key: 'schedule_variance',
    name: 'Amortization Schedule Variance',
    description: 'Only checks accounts with amortization schedules - flags when actual GL activity differs from scheduled amount',
    severity: 'high',
    scope: 'ALL',
    rule_type: 'schedule_variance',
    threshold_abs: 1,
  },
  {
    key: 'mom_pct_10',
    name: 'MoM % > 10%',
    description: 'Flags accounts with month-over-month % change above 10%',
    severity: 'medium',
    scope: 'ALL',
    variance_mode: 'PCT_DELTA',
    variance_threshold: 0.10,
    variance_basis: 'PRIOR_MONTH',
  },
  {
    key: 'mom_abs_1000',
    name: 'MoM $ > 1,000',
    description: 'Flags accounts with month-over-month $ change above 1,000',
    severity: 'medium',
    scope: 'ALL',
    variance_mode: 'ABS_DELTA',
    variance_threshold: 1000,
    variance_basis: 'PRIOR_MONTH',
  },
  {
    key: 'zero_balance',
    name: 'Zero balance',
    description: 'Flags accounts that should be zero but are not',
    severity: 'high',
    scope: 'ALL',
    threshold_abs: 1,
  },
  {
    key: 'unexpected_activity',
    name: 'Unexpected activity',
    description: 'Flags non-zero activity in usually quiet accounts',
    severity: 'high',
    scope: 'ACCOUNT_MATCH',
    account_match: 'suspense',
    threshold_abs: 1,
  },
  {
    key: 'sign_check',
    name: 'Sign check',
    description: 'Flags if balance sign is unexpected',
    severity: 'medium',
    scope: 'ACCOUNT_MATCH',
    account_match: 'revenue',
    threshold_neg: 0,
  },
]

export const PROJECT_RULE_TEMPLATES: RuleTemplate[] = [
  {
    key: 'mom_pct_revenue',
    name: 'MoM % Revenue > X',
    description: 'Flags project revenue % change vs prior month above threshold',
    domain: 'PROJECT_PNL',
    metric: 'revenue',
    severity: 'medium',
    scope: 'ALL',
    variance_mode: 'PCT_DELTA',
    variance_threshold: 0.1,
    variance_basis: 'PRIOR_MONTH',
    target: 'project_pnl',
  },
  {
    key: 'mom_abs_revenue',
    name: 'MoM $ Revenue > X',
    description: 'Flags project revenue $ change vs prior month above threshold',
    domain: 'PROJECT_PNL',
    metric: 'revenue',
    severity: 'medium',
    scope: 'ALL',
    variance_mode: 'ABS_DELTA',
    variance_threshold: 1000,
    variance_basis: 'PRIOR_MONTH',
    target: 'project_pnl',
  },
  {
    key: 'mom_pct_cogs',
    name: 'MoM % COGS > X',
    description: 'Flags project COGS % change vs prior month above threshold',
    domain: 'PROJECT_PNL',
    metric: 'cogs',
    severity: 'medium',
    scope: 'ALL',
    variance_mode: 'PCT_DELTA',
    variance_threshold: 0.1,
    variance_basis: 'PRIOR_MONTH',
    target: 'project_pnl',
  },
  {
    key: 'mom_abs_cogs',
    name: 'MoM $ COGS > X',
    description: 'Flags project COGS $ change vs prior month above threshold',
    domain: 'PROJECT_PNL',
    metric: 'cogs',
    severity: 'medium',
    scope: 'ALL',
    variance_mode: 'ABS_DELTA',
    variance_threshold: 1000,
    variance_basis: 'PRIOR_MONTH',
    target: 'project_pnl',
  },
  {
    key: 'mom_pct_gp',
    name: 'MoM % Gross Profit > X',
    description: 'Flags project GP % change vs prior month above threshold',
    domain: 'PROJECT_PNL',
    metric: 'gross_profit',
    severity: 'high',
    scope: 'ALL',
    variance_mode: 'PCT_DELTA',
    variance_threshold: 0.1,
    variance_basis: 'PRIOR_MONTH',
    target: 'project_pnl',
  },
  {
    key: 'mom_abs_gp',
    name: 'MoM $ Gross Profit > X',
    description: 'Flags project GP $ change vs prior month above threshold',
    domain: 'PROJECT_PNL',
    metric: 'gross_profit',
    severity: 'high',
    scope: 'ALL',
    variance_mode: 'ABS_DELTA',
    variance_threshold: 1000,
    variance_basis: 'PRIOR_MONTH',
    target: 'project_pnl',
  },
  {
    key: 'gp_loss',
    name: 'Gross Profit < -X',
    description: 'Flags project gross profit below negative threshold',
    domain: 'PROJECT_PNL',
    metric: 'gross_profit',
    severity: 'high',
    scope: 'ALL',
    threshold_neg: -500,
    target: 'project_pnl',
  },
  {
    key: 'not_specified_revenue',
    name: 'Not Specified Revenue > X% of total',
    description: 'Flags when revenue in Not Specified exceeds threshold % of total',
    domain: 'PROJECT_PNL',
    metric: 'revenue',
    severity: 'high',
    scope: 'ALL',
    threshold_abs: 0.1,
    target: 'not_specified_ratio',
  },
  {
    key: 'revenue_less_than_zero',
    name: 'Revenue items < 0',
    description: 'Flags projects with negative revenue',
    domain: 'PROJECT_PNL',
    metric: 'revenue',
    severity: 'high',
    scope: 'ALL',
    rule_type: 'revenue_items_less_than_zero',
  },
  {
    key: 'cogs_greater_than_revenue',
    name: 'COGS > Revenue',
    description: 'Flags projects where COGS exceeds Revenue',
    domain: 'PROJECT_PNL',
    metric: 'cogs',
    severity: 'high',
    scope: 'ALL',
    rule_type: 'cogs_greater_than_revenue',
  },
  {
    key: 'gp_percent_threshold',
    name: 'GP % < Threshold',
    description: 'Flags projects with Gross Profit % below threshold',
    domain: 'PROJECT_PNL',
    metric: 'gp_percent',
    severity: 'high',
    scope: 'ALL',
    rule_type: 'gp_percent_threshold',
    threshold_abs: 0.20,
  },
  {
    key: 'gp_negative',
    name: 'GP < 0',
    description: 'Flags projects with negative Gross Profit (loss-making)',
    domain: 'PROJECT_PNL',
    metric: 'gross_profit',
    severity: 'critical',
    scope: 'ALL',
    rule_type: 'gp_negative',
  },
  {
    key: 'revenue_no_cogs',
    name: 'Revenue > 0 AND COGS = 0',
    description: 'Flags projects with revenue but zero COGS — possible missing cost allocation',
    domain: 'PROJECT_PNL',
    metric: 'revenue',
    severity: 'high',
    scope: 'ALL',
    rule_type: 'revenue_no_cogs',
  },
  {
    key: 'cogs_no_revenue',
    name: 'COGS > 0 AND Revenue = 0',
    description: 'Flags projects with COGS but zero revenue — possible unrecognised revenue',
    domain: 'PROJECT_PNL',
    metric: 'cogs',
    severity: 'high',
    scope: 'ALL',
    rule_type: 'cogs_no_revenue',
  },
  {
    key: 'new_reactivated_project',
    name: 'New / Reactivated Project',
    description: 'Flags customers with activity this month but none last month',
    domain: 'PROJECT_PNL',
    metric: 'revenue',
    severity: 'medium',
    scope: 'ALL',
    rule_type: 'new_reactivated_project',
  },
  {
    key: 'concentration',
    name: 'Top 3 Customer Concentration',
    description: 'Flags if top-3 customers exceed X% of total revenue',
    domain: 'PROJECT_PNL',
    metric: 'revenue',
    severity: 'high',
    scope: 'ALL',
    rule_type: 'concentration',
    threshold_abs: 0.60,
  },
]
