"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { formatCurrency } from "@/lib/formatCurrency";
import { REPORT_TABLE_STYLES } from "@/components/ReportTable";
import { Button } from "@/components/ui/button";

type ScheduleType = "PREPAID" | "FIXED_ASSET" | "LOAN" | "OTHER";
type ScheduleStatus = "DRAFT" | "ACTIVE" | "CLOSED";
type LineType = "ADDITION" | "REDUCTION" | "ADJUSTMENT";

type TbAccount = {
  accountId: string;
  accountName: string;
  accountNumber?: string;
  beginning: number;
  debit: number;
  credit: number;
  ending: number;
};

export type ScheduleFormModel = {
  id?: string;
  name: string;
  type: ScheduleType;
  glAccountId: string;
  glAccountName: string;
  glAccountNumber?: string | null;
  openingBalance: number;
  additions: number;
  reductions: number;
  activityExpense: number;
  endingBalance?: number;
  tbEndingBalance?: number | null;
  varianceToTB?: number | null;
  status: ScheduleStatus;
  notes?: string | null;
  preparedBy?: string | null;
  preparedAt?: string | null;
  reviewedBy?: string | null;
  reviewedAt?: string | null;
  lockAccount?: boolean;
  lockPeriod?: boolean;
  lines?: ScheduleLineModel[];
  amortMethod?: "NONE" | "STRAIGHT_LINE";
  amortStartDate?: string | null;
  amortEndDate?: string | null;
  amortMonthlyAmount?: number | null;
  amortAutoGenerated?: boolean;
};

type ScheduleLineModel = {
  id?: string;
  lineType: LineType;
  lineDate: string;
  description: string;
  reference?: string | null;
  vendor?: string | null;
  amount: number;
};

type Props = {
  orgId: string;
  orgName?: string | null;
  periodStart: string | null;
  periodEnd: string | null;
  mode: "create" | "edit";
  initialSchedule?: ScheduleFormModel | null;
  readOnly?: boolean;
};

const typeLabel = (type: ScheduleType) => {
  if (type === "PREPAID") return "Amortization";
  if (type === "FIXED_ASSET") return "Depreciation";
  if (type === "LOAN") return "Interest (if tracked here)";
  return "Activity Expense";
};

const toNumber = (v: any) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
};

export function ScheduleForm({
  orgId,
  orgName,
  periodStart,
  periodEnd,
  mode,
  initialSchedule,
  readOnly = false,
}: Props) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const amortRef = useRef<HTMLDivElement | null>(null);
  const [accounts, setAccounts] = useState<TbAccount[]>([]);
  const [loadingAccounts, setLoadingAccounts] = useState(false);
  const [accountSearch, setAccountSearch] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [userTouchedStatus, setUserTouchedStatus] = useState(false);
  const [status, setStatus] = useState<ScheduleStatus>(initialSchedule?.status || "ACTIVE");
  const [lines, setLines] = useState<ScheduleLineModel[]>(initialSchedule?.lines || []);
  const [lineDraft, setLineDraft] = useState<ScheduleLineModel>({
    lineType: "ADDITION",
    lineDate: periodStart || "",
    description: "",
    reference: "",
    vendor: "",
    amount: 0,
  });
  const lockAccount = initialSchedule?.lockAccount ?? false;
  const lockPeriod = initialSchedule?.lockPeriod ?? false;
  const [amortMethod, setAmortMethod] = useState<"NONE" | "STRAIGHT_LINE">(
    (initialSchedule?.amortMethod as any) || "NONE"
  );
  const [amortStartDate, setAmortStartDate] = useState<string | null>(initialSchedule?.amortStartDate || null);
  const [amortEndDate, setAmortEndDate] = useState<string | null>(initialSchedule?.amortEndDate || null);
  const [amortMonthlyAmount, setAmortMonthlyAmount] = useState<number | null>(
    initialSchedule?.amortMonthlyAmount ?? null
  );
  const [amortAutoGenerated, setAmortAutoGenerated] = useState<boolean>(initialSchedule?.amortAutoGenerated ?? false);

  const [form, setForm] = useState<ScheduleFormModel>(() => ({
    name: initialSchedule?.name || "",
    type: initialSchedule?.type || "PREPAID",
    glAccountId: initialSchedule?.glAccountId || "",
    glAccountName: initialSchedule?.glAccountName || "",
    glAccountNumber: initialSchedule?.glAccountNumber || "",
    openingBalance: initialSchedule?.openingBalance ?? 0,
    additions: initialSchedule?.additions ?? 0,
    reductions: initialSchedule?.reductions ?? 0,
    activityExpense: initialSchedule?.activityExpense ?? 0,
    status: initialSchedule?.status || "ACTIVE",
    notes: initialSchedule?.notes || "",
    tbEndingBalance: initialSchedule?.tbEndingBalance ?? null,
    preparedBy: initialSchedule?.preparedBy || undefined,
    preparedAt: initialSchedule?.preparedAt || undefined,
    reviewedBy: initialSchedule?.reviewedBy || undefined,
    reviewedAt: initialSchedule?.reviewedAt || undefined,
    lockAccount: initialSchedule?.lockAccount,
    lockPeriod: initialSchedule?.lockPeriod,
    amortMethod: (initialSchedule?.amortMethod as any) || "NONE",
    amortStartDate: initialSchedule?.amortStartDate || null,
    amortEndDate: initialSchedule?.amortEndDate || null,
    amortMonthlyAmount: initialSchedule?.amortMonthlyAmount ?? null,
    amortAutoGenerated: initialSchedule?.amortAutoGenerated ?? false,
  }));

  const filteredAccounts = useMemo(() => {
    const q = accountSearch.trim().toLowerCase();
    if (!q) return accounts;
    return accounts.filter((a) =>
      `${a.accountId} ${a.accountName} ${a.accountNumber || ""}`.toLowerCase().includes(q),
    );
  }, [accounts, accountSearch]);

  const selectedAccount = useMemo(
    () => accounts.find((a) => a.accountId === form.glAccountId),
    [accounts, form.glAccountId],
  );

  const endingBalance = useMemo(() => {
    const hasLines = lines.length > 0;
    const additionsFromLines = lines
      .filter((l) => l.lineType === "ADDITION")
      .reduce((sum, l) => sum + toNumber(l.amount), 0);
    const reductionsFromLines = lines
      .filter((l) => l.lineType === "REDUCTION")
      .reduce((sum, l) => sum + toNumber(l.amount), 0);
    const adjustmentsFromLines = lines
      .filter((l) => l.lineType === "ADJUSTMENT")
      .reduce((sum, l) => sum + toNumber(l.amount), 0);
    const autoAmortFromLines = lines
      .filter((l) => l.lineType === "ADJUSTMENT" && (l as any).isAutoGenerated)
      .reduce((sum, l) => sum + toNumber(l.amount), 0);

    const additions = hasLines ? additionsFromLines : toNumber(form.additions);
    const reductions = hasLines ? reductionsFromLines : toNumber(form.reductions);
    const adjustments = hasLines ? adjustmentsFromLines : 0;

    return (
      toNumber(form.openingBalance) +
      additions -
      reductions +
      adjustments -
      (toNumber(form.activityExpense) + autoAmortFromLines)
    );
  }, [form.openingBalance, form.additions, form.reductions, form.activityExpense, lines]);

  const varianceToTB = useMemo(() => {
    if (form.tbEndingBalance === null || form.tbEndingBalance === undefined) return null;
    return endingBalance - toNumber(form.tbEndingBalance);
  }, [endingBalance, form.tbEndingBalance]);

  useEffect(() => {
    setForm((prev) => ({ ...prev, endingBalance, varianceToTB: varianceToTB ?? undefined }));
    if (!userTouchedStatus) {
      const autoStatus = Math.abs(varianceToTB ?? 0) > 0.01 ? "DRAFT" : "ACTIVE";
      setStatus(autoStatus);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [endingBalance, varianceToTB]);

  const loadAccounts = async () => {
    if (!orgId || !periodStart || !periodEnd) return;
    setLoadingAccounts(true);
    setError(null);
    try {
      const qs = new URLSearchParams({
        orgId,
        periodStart,
        periodEnd,
      }).toString();
      const resp = await fetch(`/api/trial-balance?${qs}`, { cache: "no-store" });
      if (!resp.ok) {
        const text = await resp.text().catch(() => "");
        throw new Error(text || `Request failed (${resp.status})`);
      }
      const data = await resp.json();
      setAccounts(data.accounts || []);
    } catch (err: any) {
      setError(err?.message || "Failed to load trial balance accounts");
    } finally {
      setLoadingAccounts(false);
    }
  };

  useEffect(() => {
    void loadAccounts();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [orgId, periodStart, periodEnd]);

  useEffect(() => {
    if (!accounts.length || !form.glAccountId) return;
    const match = accounts.find((a) => a.accountId === form.glAccountId);
    if (match) {
      setForm((prev) => ({
        ...prev,
        glAccountName: match.accountName,
        glAccountNumber: match.accountNumber,
        tbEndingBalance: match.ending,
      }));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accounts]);

  const handleAccountChange = (accountId: string) => {
    const acc = accounts.find((a) => a.accountId === accountId);
    setForm((prev) => ({
      ...prev,
      glAccountId: accountId,
      glAccountName: acc?.accountName || "",
      glAccountNumber: acc?.accountNumber || "",
      tbEndingBalance: acc?.ending ?? null,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (readOnly) return;
    if (!form.name.trim()) {
      setError("Name is required");
      return;
    }
    if (!form.glAccountId) {
      setError("GL account is required");
      return;
    }

    // Client-side rule checks
    if ((status === "ACTIVE" || status === "CLOSED") && (form.tbEndingBalance === null || form.tbEndingBalance === undefined)) {
      setError("TB ending balance required for Active/Closed");
      return;
    }
    if ((status === "ACTIVE" || status === "CLOSED") && Math.abs(varianceToTB ?? 0) > 0.01) {
      setError("Variance must be within ±0.01 for Active/Closed");
      return;
    }
    if ((status === "ACTIVE" || status === "CLOSED") && (!form.reviewedBy || !form.reviewedAt)) {
      setError("Reviewed By and Reviewed At are required for Active/Closed");
      return;
    }
    if (initialSchedule?.status === "CLOSED" || readOnly) {
      setError("Schedule is closed and read-only");
      return;
    }

    setSubmitting(true);
    setError(null);
    try {
      const payload = {
        orgId,
        periodStart,
        periodEnd,
        name: form.name,
        type: form.type,
        glAccountId: form.glAccountId,
        glAccountName: form.glAccountName,
        glAccountNumber: form.glAccountNumber,
        openingBalance: toNumber(form.openingBalance),
        additions: toNumber(form.additions),
        reductions: toNumber(form.reductions),
        activityExpense: toNumber(form.activityExpense),
        status,
        notes: form.notes,
        preparedBy: form.preparedBy,
        preparedAt: form.preparedAt,
        reviewedBy: form.reviewedBy,
        reviewedAt: form.reviewedAt,
        lockAccount: lockAccount || form.lockAccount,
        lockPeriod: lockPeriod || form.lockPeriod,
        lines,
        amortMethod,
        amortStartDate,
        amortEndDate,
        amortMonthlyAmount,
        amortAutoGenerated,
      };
      const resp = await fetch(
        mode === "create" ? "/api/schedules" : `/api/schedules/${initialSchedule?.id}`,
        {
          method: mode === "create" ? "POST" : "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        },
      );
      if (!resp.ok) {
        const text = await resp.text().catch(() => "");
        throw new Error(text || `Request failed (${resp.status})`);
      }
      router.push("/schedules");
      router.refresh();
    } catch (err: any) {
      setError(err?.message || "Failed to save schedule");
    } finally {
      setSubmitting(false);
    }
  };

  const varianceWarning =
    varianceToTB !== null && Math.abs(varianceToTB) > 0.01
      ? "Schedule does not tie to Trial Balance. You can save as Draft."
      : null;

  const hasLines = lines.length > 0;
  const additionsFromLines = lines
    .filter((l) => l.lineType === "ADDITION")
    .reduce((sum, l) => sum + toNumber(l.amount), 0);
  const reductionsFromLines = lines
    .filter((l) => l.lineType === "REDUCTION")
    .reduce((sum, l) => sum + toNumber(l.amount), 0);
  const adjustmentsFromLines = lines
    .filter((l) => l.lineType === "ADJUSTMENT")
    .reduce((sum, l) => sum + toNumber(l.amount), 0);

  const disableManualRollforward = hasLines;
  const showTbWarning = form.tbEndingBalance === null || form.tbEndingBalance === undefined;
  const needsReview = status === "ACTIVE" && (!form.reviewedBy || !form.reviewedAt);
  const varianceOut = varianceToTB !== null && Math.abs(varianceToTB) > 0.01;
  const isPrepaid = form.type === "PREPAID";

  // Auto-scroll to amortization section if focus=amortization
  useEffect(() => {
    const focus = searchParams?.get("focus");
    if (focus === "amortization" && amortRef.current) {
      amortRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, [searchParams]);

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">
              {mode === "create" ? "New Schedule" : readOnly ? "View Schedule" : "Edit Schedule"}
            </h1>
            <p className="text-sm text-slate-600">
              Org: {orgName || orgId} • Period: {periodStart || "—"} → {periodEnd || "—"}
            </p>
          </div>
          {!readOnly && (
            <Button variant="primary" type="submit" disabled={submitting || !orgId || !periodStart || !periodEnd}>
              {submitting ? "Saving..." : "Save Schedule"}
            </Button>
          )}
        </div>
        {isPrepaid && (
          <div className="flex gap-2 text-sm">
            <Button
              type="button"
              variant="ghost"
              onClick={() => amortRef.current?.scrollIntoView({ behavior: "smooth", block: "start" })}
            >
              Go to Amortization
            </Button>
          </div>
        )}

        {error && (
          <div className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Schedule Name</label>
            <input
              type="text"
              value={form.name}
              onChange={(e) => setForm((prev) => ({ ...prev, name: e.target.value }))}
              disabled={readOnly}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
              required
            />
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Schedule Type</label>
            <select
              value={form.type}
              onChange={(e) =>
                setForm((prev) => ({ ...prev, type: e.target.value as ScheduleType }))
              }
              disabled={readOnly}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            >
              <option value="PREPAID">Prepaid</option>
              <option value="FIXED_ASSET">Fixed Asset</option>
              <option value="LOAN">Loan</option>
              <option value="OTHER">Other</option>
            </select>
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">GL Account</label>
            <input
              type="text"
              placeholder="Search accounts..."
              value={accountSearch}
              onChange={(e) => setAccountSearch(e.target.value)}
              disabled={readOnly || lockAccount || !!initialSchedule?.id}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
            <select
              value={form.glAccountId}
              onChange={(e) => handleAccountChange(e.target.value)}
              disabled={readOnly || loadingAccounts || lockAccount || !!initialSchedule?.id}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            >
              <option value="">Select account…</option>
              {filteredAccounts.map((a) => (
                <option key={a.accountId} value={a.accountId}>
                  {a.accountId} — {a.accountName} (Ending: {formatCurrency(a.ending, true)})
                </option>
              ))}
            </select>
            {loadingAccounts && <p className="text-xs text-slate-500">Loading trial balance accounts…</p>}
            {(lockAccount || initialSchedule?.id) && (
              <p className="text-xs text-slate-500">GL account and period are locked after creation.</p>
            )}
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Notes</label>
            <textarea
              value={form.notes || ""}
              onChange={(e) => setForm((prev) => ({ ...prev, notes: e.target.value }))}
              disabled={readOnly}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
              rows={4}
            />
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Opening Balance</label>
            <input
              type="number"
              step="0.01"
              value={form.openingBalance}
              onChange={(e) =>
                setForm((prev) => ({ ...prev, openingBalance: toNumber(e.target.value) }))
              }
              disabled={readOnly}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Additions</label>
            <input
              type="number"
              step="0.01"
              value={disableManualRollforward ? additionsFromLines : form.additions}
              onChange={(e) => setForm((prev) => ({ ...prev, additions: toNumber(e.target.value) }))}
              disabled={readOnly || disableManualRollforward}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
            {disableManualRollforward && <p className="text-xs text-slate-500">Driven by line items.</p>}
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Reductions</label>
            <input
              type="number"
              step="0.01"
              value={disableManualRollforward ? reductionsFromLines : form.reductions}
              onChange={(e) => setForm((prev) => ({ ...prev, reductions: toNumber(e.target.value) }))}
              disabled={readOnly || disableManualRollforward}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
            {disableManualRollforward && <p className="text-xs text-slate-500">Driven by line items.</p>}
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">{typeLabel(form.type)}</label>
            <input
              type="number"
              step="0.01"
              value={form.activityExpense}
              onChange={(e) =>
                setForm((prev) => ({ ...prev, activityExpense: Math.max(0, toNumber(e.target.value)) }))
              }
              disabled={readOnly}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Status</label>
            <select
              value={status}
              onChange={(e) => {
                setUserTouchedStatus(true);
                setStatus(e.target.value as ScheduleStatus);
              }}
              disabled={readOnly}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            >
              <option value="DRAFT">Draft</option>
              <option value="ACTIVE">Active</option>
              <option value="CLOSED">Closed</option>
            </select>
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Reviewed By</label>
            <input
              type="text"
              value={form.reviewedBy || ""}
              onChange={(e) => setForm((prev) => ({ ...prev, reviewedBy: e.target.value }))}
              disabled={readOnly}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Reviewed At</label>
            <input
              type="date"
              value={form.reviewedAt ? form.reviewedAt.slice(0, 10) : ""}
              onChange={(e) => setForm((prev) => ({ ...prev, reviewedAt: e.target.value }))}
              disabled={readOnly}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Prepared By</label>
            <input
              type="text"
              value={form.preparedBy || ""}
              onChange={(e) => setForm((prev) => ({ ...prev, preparedBy: e.target.value }))}
              disabled={readOnly || !!initialSchedule?.preparedBy}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
          </div>

          <div className="space-y-3">
            <label className="text-sm font-semibold text-slate-800">Prepared At</label>
            <input
              type="datetime-local"
              value={form.preparedAt ? form.preparedAt.slice(0, 16) : ""}
              onChange={(e) => setForm((prev) => ({ ...prev, preparedAt: e.target.value }))}
              disabled={readOnly || !!initialSchedule?.preparedAt}
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none disabled:bg-slate-100"
            />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 rounded-xl border border-slate-200 bg-slate-50/60 p-4">
          <div>
            <div className="text-xs uppercase tracking-wide text-slate-600">Calculated Ending Balance</div>
            <div className="text-xl font-semibold text-slate-900">{formatCurrency(endingBalance, true)}</div>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wide text-slate-600">TB Ending Balance</div>
            <div className="text-xl font-semibold text-slate-900">
              {formatCurrency(form.tbEndingBalance ?? null, true)}
            </div>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wide text-slate-600">Variance to TB</div>
            <div
              className={`text-xl font-semibold ${
                varianceToTB !== null && Math.abs(varianceToTB) > 0.01 ? "text-amber-700" : "text-slate-900"
              }`}
            >
              {formatCurrency(varianceToTB, true)}
            </div>
          </div>
        </div>

        {varianceWarning && (
          <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            {varianceWarning}
          </div>
        )}

        {showTbWarning && (
          <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            Trial Balance ending balance not loaded.
          </div>
        )}
        {needsReview && (
          <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            Active schedules require Reviewed By and Reviewed At.
          </div>
        )}
        {varianceOut && (
          <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            Variance exceeds ±0.01.
          </div>
        )}

        {/* Amortization for PREPAID */}
        {isPrepaid && (
          <div ref={amortRef} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold text-slate-900">Amortization</h2>
                <p className="text-sm text-slate-600">Generate monthly amortization adjustments.</p>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
              <div>
                <label className="text-sm font-semibold text-slate-800">Method</label>
                <select
                  value={amortMethod}
                  onChange={(e) => setAmortMethod(e.target.value as any)}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                >
                  <option value="NONE">None</option>
                  <option value="STRAIGHT_LINE">Straight Line</option>
                </select>
              </div>
              <div>
                <label className="text-sm font-semibold text-slate-800">Start Date</label>
                <input
                  type="date"
                  value={amortStartDate || ""}
                  onChange={(e) => setAmortStartDate(e.target.value || null)}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                />
              </div>
              <div>
                <label className="text-sm font-semibold text-slate-800">End Date</label>
                <input
                  type="date"
                  value={amortEndDate || ""}
                  onChange={(e) => setAmortEndDate(e.target.value || null)}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                />
              </div>
              <div>
                <label className="text-sm font-semibold text-slate-800">Monthly Amount</label>
                <input
                  type="number"
                  step="0.01"
                  value={amortMonthlyAmount ?? ""}
                  onChange={(e) => setAmortMonthlyAmount(toNumber(e.target.value))}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                />
              </div>
            </div>
            <div className="flex gap-3 items-center">
              <Button
                type="button"
                variant="primary"
                disabled={
                  amortMethod !== "STRAIGHT_LINE" ||
                  !amortStartDate ||
                  !amortEndDate ||
                  new Date(amortEndDate) < new Date(amortStartDate) ||
                  status === "CLOSED"
                }
                onClick={() => {
                  if (!amortStartDate || !amortEndDate) {
                    setError("Amortization start and end dates are required");
                    return;
                  }
                  const start = new Date(amortStartDate + "T00:00:00Z");
                  const end = new Date(amortEndDate + "T00:00:00Z");
                  if (end < start) {
                    setError("Amortization end must be on/after start");
                    return;
                  }
                  if (status === "ACTIVE" && !confirm("Generate amortization lines for an Active schedule?")) {
                    return;
                  }
                  const months: Date[] = [];
                  const cur = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), 1));
                  const endMonth = end.getUTCFullYear() * 12 + end.getUTCMonth();
                  while (cur.getUTCFullYear() * 12 + cur.getUTCMonth() <= endMonth) {
                    const last = new Date(Date.UTC(cur.getUTCFullYear(), cur.getUTCMonth() + 1, 0));
                    months.push(last);
                    cur.setUTCMonth(cur.getUTCMonth() + 1);
                  }
                  const total = form.openingBalance + (hasLines ? additionsFromLines : form.additions);
                  const monthsCount = months.length || 1;
                  const base = Number((total / monthsCount).toFixed(2));
                  const genLines = months.map((d, idx) => ({
                    lineType: "ADJUSTMENT" as LineType,
                    lineDate: d.toISOString().slice(0, 10),
                    description: `Amortization - ${form.name}`,
                    reference: null,
                    vendor: null,
                    amount: base,
                    id: `amort-${idx}`,
                    isAutoGenerated: true,
                    generatedSource: "AMORTIZATION",
                  })) as any;
                  const sumBase = genLines.reduce((s, l) => s + toNumber(l.amount), 0);
                  const remainder = Number((total - sumBase).toFixed(2));
                  if (genLines.length > 0) {
                    genLines[genLines.length - 1].amount = Number((genLines[genLines.length - 1].amount + remainder).toFixed(2));
                  }
                  const nonAuto = lines.filter((l: any) => !(l as any).isAutoGenerated);
                  setLines([...nonAuto, ...genLines]);
                  setAmortAutoGenerated(true);
                  setAmortMonthlyAmount(base);
                  setError(null);
                }}
              >
                Generate Amortization Lines
              </Button>
              <span className="text-sm text-slate-600">
                {amortStartDate && amortEndDate
                  ? `From ${amortStartDate} to ${amortEndDate}`
                  : "Set start and end dates"}
              </span>
            </div>
          </div>
        )}

        {/* Line Items */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-lg font-semibold text-slate-900">Line Items</h2>
              <p className="text-sm text-slate-600">
                Additions / Reductions / Adjustments roll into totals automatically.
              </p>
            </div>
            {!readOnly && (
              <Button
                type="button"
                variant="ghost"
                onClick={() => {
                  setLineDraft({
                    lineType: "ADDITION",
                    lineDate: periodStart || "",
                    description: "",
                    reference: "",
                    vendor: "",
                    amount: 0,
                  });
                }}
              >
                Add Line
              </Button>
            )}
          </div>

          {lines.length === 0 && (
            <div className="rounded-md border border-dashed border-slate-300 p-4 text-sm text-slate-600">
              No line items yet. Add lines to support this balance.
            </div>
          )}

          {lines.length > 0 && (
            <div className={REPORT_TABLE_STYLES.container}>
              <table className={REPORT_TABLE_STYLES.table}>
                <thead className={REPORT_TABLE_STYLES.thead}>
                  <tr>
                    <th className={REPORT_TABLE_STYLES.th}>Date</th>
                    <th className={REPORT_TABLE_STYLES.th}>Type</th>
                    <th className={REPORT_TABLE_STYLES.th}>Description</th>
                    <th className={REPORT_TABLE_STYLES.th}>Reference</th>
                    <th className={REPORT_TABLE_STYLES.th}>Vendor</th>
                    <th className={REPORT_TABLE_STYLES.thNumeric}>Amount</th>
                    <th className={REPORT_TABLE_STYLES.th}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {lines.map((l, idx) => (
                    <tr key={l.id || idx} className={REPORT_TABLE_STYLES.tr}>
                      <td className={REPORT_TABLE_STYLES.td}>{l.lineDate}</td>
                      <td className={REPORT_TABLE_STYLES.td}>{l.lineType}</td>
                      <td className={REPORT_TABLE_STYLES.td}>{l.description}</td>
                      <td className={REPORT_TABLE_STYLES.td}>{l.reference || "—"}</td>
                      <td className={REPORT_TABLE_STYLES.td}>{l.vendor || "—"}</td>
                      <td className={REPORT_TABLE_STYLES.tdNumeric}>{formatCurrency(l.amount, true)}</td>
                      <td className={REPORT_TABLE_STYLES.td}>
                        {!readOnly && (
                          <div className="flex gap-2 text-sm">
                            <button
                              type="button"
                              className="text-blue-600 hover:underline"
                              onClick={() => setLineDraft(l)}
                            >
                              Edit
                            </button>
                            <button
                              type="button"
                              className="text-red-600 hover:underline"
                              onClick={() => setLines((prev) => prev.filter((_, i) => i !== idx))}
                            >
                              Delete
                            </button>
                          </div>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {!readOnly && (
            <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm space-y-3">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <div>
                  <label className="text-sm font-semibold text-slate-800">Date</label>
                  <input
                    type="date"
                    value={lineDraft.lineDate || ""}
                    onChange={(e) => setLineDraft((p) => ({ ...p, lineDate: e.target.value }))}
                    className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-800">Type</label>
                  <select
                    value={lineDraft.lineType}
                    onChange={(e) => setLineDraft((p) => ({ ...p, lineType: e.target.value as LineType }))}
                    className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
                  >
                    <option value="ADDITION">Addition</option>
                    <option value="REDUCTION">Reduction</option>
                    <option value="ADJUSTMENT">Adjustment</option>
                  </select>
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-800">Amount</label>
                  <input
                    type="number"
                    step="0.01"
                    value={lineDraft.amount}
                    onChange={(e) => setLineDraft((p) => ({ ...p, amount: toNumber(e.target.value) }))}
                    className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
                  />
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <div className="md:col-span-3">
                  <label className="text-sm font-semibold text-slate-800">Description</label>
                  <input
                    type="text"
                    value={lineDraft.description}
                    onChange={(e) => setLineDraft((p) => ({ ...p, description: e.target.value }))}
                    className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-800">Reference</label>
                  <input
                    type="text"
                    value={lineDraft.reference || ""}
                    onChange={(e) => setLineDraft((p) => ({ ...p, reference: e.target.value }))}
                    className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="text-sm font-semibold text-slate-800">Vendor</label>
                  <input
                    type="text"
                    value={lineDraft.vendor || ""}
                    onChange={(e) => setLineDraft((p) => ({ ...p, vendor: e.target.value }))}
                    className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
                  />
                </div>
              </div>
              <div className="flex gap-3">
                <Button
                  type="button"
                  variant="primary"
                  onClick={() => {
                    if (!lineDraft.lineDate || !lineDraft.description) {
                      setError("Line date and description are required");
                      return;
                    }
                    setError(null);
                    setLines((prev) => {
                      // If editing existing line (match by id), replace; else append
                      if (lineDraft.id) {
                        return prev.map((l) => (l.id === lineDraft.id ? lineDraft : l));
                      }
                      return [...prev, { ...lineDraft, id: `${Date.now()}-${prev.length}` }];
                    });
                    setLineDraft({
                      lineType: "ADDITION",
                      lineDate: periodStart || "",
                      description: "",
                      reference: "",
                      vendor: "",
                      amount: 0,
                    });
                  }}
                >
                  Save Line
                </Button>
                <Button
                  type="button"
                  variant="ghost"
                  onClick={() =>
                    setLineDraft({
                      lineType: "ADDITION",
                      lineDate: periodStart || "",
                      description: "",
                      reference: "",
                      vendor: "",
                      amount: 0,
                    })
                  }
                >
                  Clear
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    </form>
  );
}
