"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { formatCurrency } from "@/lib/formatCurrency";
import { REPORT_TABLE_STYLES } from "@/components/ReportTable";
import { Button } from "@/components/ui/button";

type ScheduleType = "PREPAID" | "FIXED_ASSET" | "LOAN" | "OTHER";
type ScheduleStatus = "DRAFT" | "ACTIVE" | "CLOSED";

export type ScheduleRow = {
  id: string;
  name: string;
  type: ScheduleType;
  glAccountId: string;
  glAccountName: string;
  glAccountNumber?: string | null;
  status: ScheduleStatus;
  endingBalance: number;
  tbEndingBalance: number | null;
  varianceToTB: number | null;
  updatedAt?: string | null;
  preparedBy?: string | null;
  reviewedBy?: string | null;
  amortAutoGenerated?: boolean;
};

type Props = {
  orgId: string;
  orgName?: string | null;
  periodStart: string | null;
  periodEnd: string | null;
};

export function SchedulesClient({ orgId, orgName, periodStart, periodEnd }: Props) {
  const router = useRouter();
  const [schedules, setSchedules] = useState<ScheduleRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState<"" | ScheduleStatus>("");
  const [typeFilter, setTypeFilter] = useState<"" | ScheduleType>("");
  const [outOfBalanceOnly, setOutOfBalanceOnly] = useState(false);

  const periodLabel = useMemo(() => {
    if (periodStart && periodEnd) return `${periodStart} → ${periodEnd}`;
    return "Select a period to view schedules";
  }, [periodStart, periodEnd]);

  const loadSchedules = async () => {
    if (!orgId || !periodStart || !periodEnd) return;
    setLoading(true);
    setError(null);
    try {
      const qs = new URLSearchParams({
        orgId,
        periodStart,
        periodEnd,
      }).toString();
      const resp = await fetch(`/api/schedules?${qs}`, { cache: "no-store" });
      if (!resp.ok) {
        const text = await resp.text().catch(() => "");
        throw new Error(text || `Request failed (${resp.status})`);
      }
      const data = await resp.json();
      setSchedules(data.schedules || []);
    } catch (err: any) {
      setError(err?.message || "Failed to load schedules");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadSchedules();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [orgId, periodStart, periodEnd]);

  const handleDelete = async (id: string) => {
    if (!confirm("Delete this schedule? This is a soft delete and can be recreated.")) return;
    await fetch(`/api/schedules/${id}`, { method: "DELETE" });
    void loadSchedules();
    router.refresh();
  };

  const filtered = useMemo(() => {
    return schedules.filter((s) => {
      if (statusFilter && s.status !== statusFilter) return false;
      if (typeFilter && s.type !== typeFilter) return false;
      const isOut = Math.abs(s.varianceToTB || 0) > 0.01 || s.tbEndingBalance === null || s.tbEndingBalance === undefined;
      if (outOfBalanceOnly && !isOut) return false;
      return true;
    });
  }, [schedules, statusFilter, typeFilter, outOfBalanceOnly]);

  const badgeClass = (s: ScheduleRow) => {
    const variance = Math.abs(s.varianceToTB || 0);
    const hasTb = s.tbEndingBalance !== null && s.tbEndingBalance !== undefined;
    const ties = hasTb && variance <= 0.01 && (s.status === "ACTIVE" || s.status === "CLOSED");
    const out = variance > 0.01 || !hasTb;
    if (ties) return "bg-emerald-100 text-emerald-700";
    if (out) return "bg-red-100 text-red-700";
    return "bg-amber-100 text-amber-700";
  };

  const badgeLabel = (s: ScheduleRow) => {
    const variance = Math.abs(s.varianceToTB || 0);
    const hasTb = s.tbEndingBalance !== null && s.tbEndingBalance !== undefined;
    const ties = hasTb && variance <= 0.01 && (s.status === "ACTIVE" || s.status === "CLOSED");
    const out = variance > 0.01 || !hasTb;
    if (ties) return "Ties";
    if (out) return "Out of balance";
    return s.status;
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Schedules</h1>
          <p className="text-sm text-slate-600">
            {orgId ? `Org: ${orgName || orgId}` : "No org selected"} • Period: {periodLabel}
          </p>
        </div>
        <Button
          variant="primary"
          onClick={() => router.push("/schedules/new")}
          disabled={!orgId || !periodStart || !periodEnd}
        >
          New Schedule
        </Button>
      </div>

      {error && (
        <div className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      )}

      <div className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
        <div className="flex items-center gap-2">
          <label className="text-sm text-slate-600">Status</label>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as any)}
            className="rounded-md border border-slate-300 px-3 py-2 text-sm"
          >
            <option value="">All</option>
            <option value="DRAFT">Draft</option>
            <option value="ACTIVE">Active</option>
            <option value="CLOSED">Closed</option>
          </select>
        </div>
        <div className="flex items-center gap-2">
          <label className="text-sm text-slate-600">Type</label>
          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value as any)}
            className="rounded-md border border-slate-300 px-3 py-2 text-sm"
          >
            <option value="">All</option>
            <option value="PREPAID">Prepaid</option>
            <option value="FIXED_ASSET">Fixed Asset</option>
            <option value="LOAN">Loan</option>
            <option value="OTHER">Other</option>
          </select>
        </div>
        <label className="flex items-center gap-2 text-sm text-slate-700">
          <input
            type="checkbox"
            checked={outOfBalanceOnly}
            onChange={(e) => setOutOfBalanceOnly(e.target.checked)}
          />
          Out of balance only
        </label>
      </div>

      <div className={`${REPORT_TABLE_STYLES.container}`}>
        <table className={REPORT_TABLE_STYLES.table}>
          <thead className={REPORT_TABLE_STYLES.thead}>
            <tr>
              <th className={REPORT_TABLE_STYLES.th}>Schedule Name</th>
              <th className={REPORT_TABLE_STYLES.th}>Type</th>
              <th className={REPORT_TABLE_STYLES.th}>GL Account</th>
              <th className={REPORT_TABLE_STYLES.th}>Status</th>
              <th className={REPORT_TABLE_STYLES.th}>Amort</th>
              <th className={REPORT_TABLE_STYLES.thNumeric}>Ending Balance</th>
              <th className={REPORT_TABLE_STYLES.thNumeric}>TB Ending</th>
              <th className={REPORT_TABLE_STYLES.thNumeric}>Variance</th>
              <th className={REPORT_TABLE_STYLES.th}>Updated</th>
              <th className={REPORT_TABLE_STYLES.th}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {loading && (
              <tr className={REPORT_TABLE_STYLES.tr}>
                <td className={REPORT_TABLE_STYLES.td} colSpan={10}>
                  Loading schedules…
                </td>
              </tr>
            )}
            {!loading && filtered.length === 0 && (
              <tr className={REPORT_TABLE_STYLES.tr}>
                <td className={REPORT_TABLE_STYLES.td} colSpan={10}>
                  No schedules found for this period.
                </td>
              </tr>
            )}
            {!loading &&
              filtered.map((s) => (
                <tr key={s.id} className={REPORT_TABLE_STYLES.tr}>
                  <td className={REPORT_TABLE_STYLES.td}>{s.name}</td>
                  <td className={REPORT_TABLE_STYLES.td}>{s.type}</td>
                  <td className={REPORT_TABLE_STYLES.td}>
                    <div className="text-sm font-semibold text-slate-900">{s.glAccountName}</div>
                    <div className="text-xs text-slate-500">
                      {s.glAccountId}
                      {s.glAccountNumber ? ` • ${s.glAccountNumber}` : ""}
                    </div>
                  </td>
                  <td className={REPORT_TABLE_STYLES.td}>
                    <span
                      className={`inline-flex rounded-full px-2 py-1 text-xs font-semibold ${badgeClass(s)}`}
                    >
                      {badgeLabel(s)}
                    </span>
                  </td>
                  <td className={REPORT_TABLE_STYLES.td}>
                    {s.type === "PREPAID" && s.amortAutoGenerated ? "✓" : "—"}
                  </td>
                  <td className={REPORT_TABLE_STYLES.tdNumeric}>{formatCurrency(s.endingBalance, true)}</td>
                  <td className={REPORT_TABLE_STYLES.tdNumeric}>{formatCurrency(s.tbEndingBalance, true)}</td>
                  <td className={REPORT_TABLE_STYLES.tdNumeric}>
                    <span className={Math.abs(s.varianceToTB || 0) > 0.01 ? "text-amber-700" : "text-slate-900"}>
                      {formatCurrency(s.varianceToTB, true)}
                    </span>
                  </td>
                  <td className={REPORT_TABLE_STYLES.td}>
                    {s.updatedAt ? new Date(s.updatedAt).toLocaleString() : "—"}
                  </td>
                  <td className={REPORT_TABLE_STYLES.td}>
                    <div className="flex gap-2 text-sm">
                      <button
                        className="text-blue-600 hover:underline"
                        onClick={() => router.push(`/schedules/${s.id}?mode=view`)}
                        type="button"
                      >
                        View
                      </button>
                      <button
                        className="text-blue-600 hover:underline"
                        onClick={() => router.push(`/schedules/${s.id}`)}
                        type="button"
                      >
                        Edit
                      </button>
                      {s.type === "PREPAID" && (
                        <button
                          className="text-blue-600 hover:underline"
                          onClick={() => router.push(`/schedules/${s.id}?focus=amortization`)}
                          type="button"
                        >
                          Amort
                        </button>
                      )}
                      <button
                        onClick={() => handleDelete(s.id)}
                        className="text-red-600 hover:underline"
                        type="button"
                      >
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
