/**
 * Schedule Variance Rule Evaluator
 * 
 * Compares actual GL activity against amortization schedules and flags
 * exceptions when the variance exceeds the configured tolerance.
 */

import { prisma } from '@/lib/db/prisma'
import { Rule, RuleResult, RuleExecutionContext } from './types'

const normalizeName = (s?: string | null) => (s || '').trim().toLowerCase()
const toNumber = (v: any) => {
  if (v == null) return 0
  if (typeof v === 'number') return v
  if (typeof v === 'string') return Number(v) || 0
  if (typeof v === 'object' && typeof (v as any).toNumber === 'function') return (v as any).toNumber()
  return Number(v) || 0
}

/**
 * Evaluate schedule variance rules
 * 
 * For each schedule with amortization, compare the expected amortization amount
 * against actual GL activity. Flag if variance exceeds threshold.
 */
export async function evaluateScheduleVariance(
    rule: Rule,
    context: RuleExecutionContext
): Promise<RuleResult[]> {
    const results: RuleResult[] = []

    // Parse period into range
    const periodDate = new Date(context.period + 'T00:00:00Z')
    const periodStart = new Date(Date.UTC(periodDate.getUTCFullYear(), periodDate.getUTCMonth(), 1))
    const periodEnd = new Date(Date.UTC(periodDate.getUTCFullYear(), periodDate.getUTCMonth() + 1, 0))

    // Get tolerance threshold from rule config (default $1.00)
    const tolerance = rule.config.scheduleVarianceTolerance ?? rule.config.threshold ?? 1.0

    // Optional account filter
    const accountMatch = rule.config.accountMatch as string | undefined

    // Fetch schedules for this org and period that have amortization configured
    const schedules = await prisma.schedule.findMany({
        where: {
            orgId: context.orgId,
            periodStart: { lte: periodEnd },
            periodEnd: { gte: periodStart },
            deletedAt: null,
            // Only schedules with amortization
            OR: [
                { amortAutoGenerated: true },
                { amortMethod: 'STRAIGHT_LINE' },
            ],
            // Optional account name filter
            ...(accountMatch ? {
                glAccountName: { contains: accountMatch, mode: 'insensitive' as const },
            } : {}),
        },
        include: {
            lines: {
                where: {
                    isAutoGenerated: true,
                    generatedSource: 'AMORTIZATION',
                    lineDate: {
                        gte: periodStart,
                        lte: periodEnd,
                    },
                },
            },
        },
    })

    if (schedules.length === 0) {
        return results
    }

    // For each schedule, compare expected vs actual
    for (const schedule of schedules) {
        // Calculate expected amortization for this period from schedule lines
        const expectedAmort = schedule.lines.reduce((sum, line) => {
            return sum + Math.abs(Number(line.amount))
        }, 0)

        // If no expected amortization, skip
        if (expectedAmort === 0 && !schedule.amortMonthlyAmount) {
            continue
        }

        // Try amortMonthlyAmount if no lines
        const expectedAmount = expectedAmort > 0
            ? expectedAmort
            : Math.abs(Number(schedule.amortMonthlyAmount || 0))

        if (expectedAmount === 0) {
            continue
        }

        // Find actual GL activity from TB period activity (debit - credit)
        const matchLine =
            context.tbLines.find((l) => (l.account_id || l.account_number || '') === (schedule.glAccountId || '')) ||
            context.tbLines.find((l) => normalizeName(l.account_name) === normalizeName(schedule.glAccountName || '')) ||
            null
        const netActivity = matchLine
            ? toNumber(matchLine.debit) - toNumber(matchLine.credit)
            : 0
        const actualAmount = Math.abs(netActivity)

        // Calculate variance
        const variance = Math.abs(expectedAmount - actualAmount)

        // Check if variance exceeds tolerance
        if (variance > tolerance) {
            results.push({
                ruleId: rule.id,
                accountId: schedule.glAccountId,
                accountName: schedule.glAccountName,
                period: context.period,
                result: 'fail',
                value: variance,
                threshold: tolerance,
                message: `Schedule "${schedule.name}" - Expected amort: $${expectedAmount.toFixed(2)}, Actual: $${actualAmount.toFixed(2)}, Variance: $${variance.toFixed(2)} exceeds tolerance of $${tolerance.toFixed(2)}`,
                metadata: {
                    scheduleId: schedule.id,
                    scheduleName: schedule.name,
                    expectedAmount,
                    actualAmount,
                    variance,
                },
            })
        } else {
            results.push({
                ruleId: rule.id,
                accountId: schedule.glAccountId,
                accountName: schedule.glAccountName,
                period: context.period,
                result: 'pass',
                value: variance,
                threshold: tolerance,
                message: `Schedule "${schedule.name}" - Variance $${variance.toFixed(2)} within tolerance of $${tolerance.toFixed(2)}`,
                metadata: {
                    scheduleId: schedule.id,
                    scheduleName: schedule.name,
                    expectedAmount,
                    actualAmount,
                    variance,
                },
            })
        }
    }

    return results
}
