import { NextRequest, NextResponse } from 'next/server'
import { Prisma } from '@prisma/client'
import { prisma } from '@/lib/db/prisma'
import { ensureOrgAccessApi } from '@/lib/auth/ensureOrgAccessApi'
import { isoToUTCDateOnly, dateToISOString } from '@/lib/dates/dateOnly'
import { fetchTrialBalanceAccounts } from '@/lib/tb/trialBalanceAccounts'

const numberOrZero = (v: any) => {
  const n = Number(v)
  return Number.isFinite(n) ? n : 0
}

const numberOrNull = (v: any) => {
  const n = Number(v)
  return Number.isFinite(n) ? n : null
}

const decimal = (v: number | null) => (v === null ? null : new Prisma.Decimal(v))

const mapSchedule = (s: any) => ({
  id: s.id,
  orgId: s.orgId,
  periodStart: dateToISOString(new Date(s.periodStart)),
  periodEnd: dateToISOString(new Date(s.periodEnd)),
  name: s.name,
  type: s.type,
  glAccountId: s.glAccountId,
  glAccountName: s.glAccountName,
  glAccountNumber: s.glAccountNumber,
  currency: s.currency,
  openingBalance: numberOrZero(s.openingBalance),
  additions: numberOrZero(s.additions),
  reductions: numberOrZero(s.reductions),
  activityExpense: numberOrZero(s.activityExpense),
  endingBalance: numberOrZero(s.endingBalance),
  tbEndingBalance: numberOrNull(s.tbEndingBalance),
  varianceToTB: numberOrNull(s.varianceToTB),
  status: s.status,
  notes: s.notes,
  preparedBy: s.preparedBy,
  preparedAt: s.preparedAt?.toISOString?.() || null,
  reviewedBy: s.reviewedBy,
  reviewedAt: s.reviewedAt?.toISOString?.() || null,
  lockAccount: !!s.lockAccount,
  lockPeriod: !!s.lockPeriod,
  amortMethod: s.amortMethod,
  amortStartDate: s.amortStartDate ? s.amortStartDate.toISOString() : null,
  amortEndDate: s.amortEndDate ? s.amortEndDate.toISOString() : null,
  amortMonthlyAmount: numberOrNull(s.amortMonthlyAmount),
  amortAutoGenerated: !!s.amortAutoGenerated,
  lines: Array.isArray(s.lines)
    ? s.lines.map((l: any) => ({
        id: l.id,
        lineType: l.lineType,
        lineDate: dateToISOString(new Date(l.lineDate)),
        description: l.description,
        reference: l.reference,
        vendor: l.vendor,
        amount: numberOrZero(l.amount),
      }))
    : [],
  createdAt: s.createdAt?.toISOString?.() || null,
  updatedAt: s.updatedAt?.toISOString?.() || null,
})

const parseDateTime = (v: any): Date | null => {
  if (!v) return null
  const d = new Date(v)
  return isNaN(d.getTime()) ? null : d
}

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) {
  try {
    if (!params?.id || params.id === 'undefined') {
      return NextResponse.json({ error: 'schedule id is required' }, { status: 400 })
    }
    if (!(prisma as any).schedule?.findUnique) {
      return NextResponse.json(
        { error: 'Prisma client not updated; run prisma generate after migration' },
        { status: 500 },
      )
    }

    const schedule = await prisma.schedule.findUnique({
      where: { id: params.id, deletedAt: null },
      include: { lines: true },
    })

    if (!schedule) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 })
    }

    await ensureOrgAccessApi(schedule.orgId)

    return NextResponse.json({ schedule: mapSchedule(schedule) })
  } catch (error: any) {
    console.error('[Schedules][GET one] error', error)
    return NextResponse.json({ error: error.message || 'Failed to load schedule' }, { status: 500 })
  }
}

export async function PATCH(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    if (!params?.id || params.id === 'undefined') {
      return NextResponse.json({ error: 'schedule id is required' }, { status: 400 })
    }
    if (!(prisma as any).schedule?.update) {
      return NextResponse.json(
        { error: 'Prisma client not updated; run prisma generate after migration' },
        { status: 500 },
      )
    }

    const existing = await prisma.schedule.findUnique({
      where: { id: params.id, deletedAt: null },
      include: { lines: true },
    })

    if (!existing) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 })
    }

    await ensureOrgAccessApi(existing.orgId)

    if (existing.status === 'CLOSED') {
      return NextResponse.json({ error: 'Schedule is closed and read-only' }, { status: 400 })
    }

    const body = await req.json()
    const name = (body.name ?? existing.name).toString().trim()
    const type = (body.type ?? existing.type).toString().toUpperCase()
    const glAccountId = existing.lockAccount ? existing.glAccountId : (body.glAccountId ?? existing.glAccountId).toString()
    const glAccountNameInput = existing.lockAccount
      ? existing.glAccountName
      : (body.glAccountName ?? existing.glAccountName ?? '').toString()
    const glAccountNumberInput =
      existing.lockAccount
        ? existing.glAccountNumber
        : body.glAccountNumber !== undefined
          ? body.glAccountNumber
            ? String(body.glAccountNumber)
            : null
          : existing.glAccountNumber
    const lines = Array.isArray(body.lines) ? body.lines : null
    const amortMethod = (body.amortMethod ?? existing.amortMethod ?? 'NONE').toString().toUpperCase()
    const amortStartDate = body.amortStartDate
      ? isoToUTCDateOnly(body.amortStartDate)
      : existing.amortStartDate ?? null
    const amortEndDate = body.amortEndDate ? isoToUTCDateOnly(body.amortEndDate) : existing.amortEndDate ?? null
    const amortMonthlyAmount =
      body.amortMonthlyAmount !== undefined
        ? numberOrZero(body.amortMonthlyAmount)
        : existing.amortMonthlyAmount
        ? numberOrZero(existing.amortMonthlyAmount)
        : null
    const amortAutoGenerated = body.amortAutoGenerated ?? existing.amortAutoGenerated ?? false

    const periodStart = existing.lockPeriod ? dateToISOString(existing.periodStart) : body.periodStart ?? dateToISOString(existing.periodStart)
    const periodEnd = existing.lockPeriod ? dateToISOString(existing.periodEnd) : body.periodEnd ?? dateToISOString(existing.periodEnd)

    const startDate = isoToUTCDateOnly(periodStart)
    const endDate = isoToUTCDateOnly(periodEnd)
    if (startDate > endDate) {
      return NextResponse.json({ error: 'periodStart must be on/before periodEnd' }, { status: 400 })
    }

    const openingBalance = numberOrZero(body.openingBalance ?? existing.openingBalance)
    const additions = numberOrZero(body.additions ?? existing.additions)
    const reductions = numberOrZero(body.reductions ?? existing.reductions)
    const activityExpenseInput = Math.max(0, numberOrZero(body.activityExpense ?? existing.activityExpense))

    const { accounts } = await fetchTrialBalanceAccounts(existing.orgId, periodStart, periodEnd)
    const tbAccount =
      accounts.find((a) => a.accountId === glAccountId) ||
      accounts.find((a) => a.accountName.toLowerCase() === glAccountNameInput.toLowerCase())

    const tbEndingBalance = tbAccount ? tbAccount.ending : null
    const resolvedAccountName = glAccountNameInput || tbAccount?.accountName || ''
    const resolvedAccountNumber = glAccountNumberInput ?? tbAccount?.accountNumber ?? null

    // If lines are provided (or existing lines present), compute roll-forward from lines
    const effectiveLines = lines ?? existing.lines ?? []
    let computedAdditions = additions
    let computedReductions = reductions
    let computedAdjustments = 0
    let autoAmortActivity = 0
    if (effectiveLines.length > 0) {
      computedAdditions = effectiveLines
        .filter((l: any) => (l.lineType || l.type || '').toString().toUpperCase() === 'ADDITION')
        .reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)
      computedReductions = effectiveLines
        .filter((l: any) => (l.lineType || l.type || '').toString().toUpperCase() === 'REDUCTION')
        .reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)
      const adjustmentLines = effectiveLines
        .filter((l: any) => (l.lineType || l.type || '').toString().toUpperCase() === 'ADJUSTMENT')
      computedAdjustments = adjustmentLines.reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)
      autoAmortActivity = adjustmentLines
        .filter((l: any) => l.isAutoGenerated || (l.generatedSource || '').toString().toUpperCase() === 'AMORTIZATION')
        .reduce((sum: number, l: any) => sum + numberOrZero(l.amount), 0)
    }

    const endingBalance =
      openingBalance + computedAdditions - computedReductions + computedAdjustments - (activityExpenseInput + autoAmortActivity)
    const varianceToTB =
      tbEndingBalance === null || tbEndingBalance === undefined ? null : endingBalance - tbEndingBalance

    const requestedStatus = (body.status ?? existing.status).toString().toUpperCase()
    const reviewedBy = body.reviewedBy ?? existing.reviewedBy ?? null
    const reviewedAtInput = body.reviewedAt ?? existing.reviewedAt ?? null
    const reviewedAt =
      reviewedAtInput instanceof Date
        ? reviewedAtInput
        : reviewedAtInput
        ? isoToUTCDateOnly(reviewedAtInput)
        : null
    const preparedAtInput = parseDateTime(body.preparedAt) || existing.preparedAt || new Date()

    const statusChecks = () => {
      if (requestedStatus === 'CLOSED') {
        if (!tbEndingBalance && tbEndingBalance !== 0) return 'TB ending balance required to close'
        if (Math.abs(varianceToTB ?? 0) > 0.01) return 'Variance must be within ±0.01 to close'
        if (!reviewedBy || !reviewedAt) return 'Reviewed By and Reviewed At are required to close'
      }
      if (requestedStatus === 'ACTIVE') {
        if (!tbEndingBalance && tbEndingBalance !== 0) return 'TB ending balance required for Active'
        if (Math.abs(varianceToTB ?? 0) > 0.01) return 'Variance must be within ±0.01 for Active'
        if (!reviewedBy || !reviewedAt) return 'Reviewed By and Reviewed At required for Active'
      }
      return null
    }
    const statusError = statusChecks()
    if (statusError) {
      return NextResponse.json({ error: statusError }, { status: 400 })
    }

    const status =
      ['DRAFT', 'ACTIVE', 'CLOSED'].includes(requestedStatus) && requestedStatus ? requestedStatus : existing.status

    const updated = await prisma.schedule.update({
      where: { id: params.id },
      data: {
        name,
        type,
        glAccountId,
        glAccountName: resolvedAccountName,
        glAccountNumber: resolvedAccountNumber,
        periodStart: startDate,
        periodEnd: endDate,
        openingBalance: decimal(openingBalance)!,
        additions: decimal(computedAdditions)!,
        reductions: decimal(computedReductions)!,
        activityExpense: decimal(activityExpenseInput + autoAmortActivity)!,
        endingBalance: decimal(endingBalance)!,
        tbEndingBalance: decimal(tbEndingBalance),
        varianceToTB: decimal(varianceToTB),
        status,
        notes: body.notes ?? existing.notes,
        preparedBy: existing.preparedBy ?? body.preparedBy ?? null,
        preparedAt: preparedAtInput,
        reviewedBy,
        reviewedAt,
        amortMethod,
        amortStartDate,
        amortEndDate,
        amortMonthlyAmount: amortMonthlyAmount !== null ? decimal(amortMonthlyAmount) : null,
        amortAutoGenerated,
      },
    })

    // Replace lines if provided
    if (lines && (prisma as any).scheduleLine?.deleteMany) {
      await prisma.scheduleLine.deleteMany({ where: { scheduleId: params.id } })
      const lineRows = lines.map((l: any) => ({
        scheduleId: params.id,
        lineType: (l.lineType || l.type || '').toString().toUpperCase(),
        lineDate: isoToUTCDateOnly(l.lineDate || l.date || periodStart),
        description: String(l.description || '').trim() || 'Line',
        reference: l.reference ? String(l.reference) : null,
        vendor: l.vendor ? String(l.vendor) : null,
        amount: new Prisma.Decimal(numberOrZero(l.amount)),
        isAutoGenerated: !!l.isAutoGenerated,
        generatedSource: (l.generatedSource || '').toString().toUpperCase() || 'NONE',
      }))
      if (lineRows.length > 0) {
        await prisma.scheduleLine.createMany({ data: lineRows })
      }
    }

    return NextResponse.json({ schedule: mapSchedule(updated) })
  } catch (error: any) {
    console.error('[Schedules][PATCH] error', error)
    return NextResponse.json({ error: error.message || 'Failed to update schedule' }, { status: 500 })
  }
}

export async function DELETE(_req: NextRequest, { params }: { params: { id: string } }) {
  try {
    if (!params?.id || params.id === 'undefined') {
      return NextResponse.json({ error: 'schedule id is required' }, { status: 400 })
    }
    if (!(prisma as any).schedule?.update) {
      return NextResponse.json(
        { error: 'Prisma client not updated; run prisma generate after migration' },
        { status: 500 },
      )
    }

    const existing = await prisma.schedule.findUnique({ where: { id: params.id } })
    if (!existing) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 })
    }

    await ensureOrgAccessApi(existing.orgId)

    await prisma.schedule.update({
      where: { id: params.id },
      data: { deletedAt: new Date() },
    })

    return NextResponse.json({ success: true })
  } catch (error: any) {
    console.error('[Schedules][DELETE] error', error)
    return NextResponse.json({ error: error.message || 'Failed to delete schedule' }, { status: 500 })
  }
}
