import { redirect } from 'next/navigation'
import { prisma } from '@/lib/db/prisma'
import { ensureOrgAccess } from '@/lib/auth/ensureOrgAccess'
import { requireScreen } from '@/lib/auth/guard'
import { Breadcrumbs } from '@/components/ui/Breadcrumbs'
import { ScheduleForm, ScheduleFormModel } from '../ScheduleForm'

export const dynamic = 'force-dynamic'
export const revalidate = 0

type Params = { params: Promise<{ id: string }>; searchParams: Promise<{ mode?: string }> }

export default async function ScheduleDetailPage({ params, searchParams }: Params) {
  await requireScreen('schedules')

  // Next.js 15+ requires awaiting params and searchParams
  const resolvedParams = await params
  const resolvedSearchParams = await searchParams

  if (!resolvedParams?.id) redirect('/schedules')

  console.log('[ScheduleDetail] hit', { id: resolvedParams?.id, mode: resolvedSearchParams?.mode })

  const schedule = await prisma.schedule.findUnique({
    where: { id: resolvedParams.id },
    include: { lines: true, org: { select: { name: true, id: true } } },
  })
  console.log('[ScheduleDetail] findUnique result', { found: !!schedule, id: resolvedParams.id })

  if (!schedule) {
    redirect('/schedules')
  }

  console.log('[ScheduleDetail] before ensureOrgAccess', { orgId: schedule.orgId })
  await ensureOrgAccess(schedule.orgId)
  console.log('[ScheduleDetail] after ensureOrgAccess')

  const periodStart = schedule.periodStart.toISOString().slice(0, 10)
  const periodEnd = schedule.periodEnd.toISOString().slice(0, 10)

  const initial: ScheduleFormModel = {
    id: schedule.id,
    name: schedule.name,
    type: schedule.type as ScheduleFormModel['type'],
    glAccountId: schedule.glAccountId,
    glAccountName: schedule.glAccountName,
    glAccountNumber: schedule.glAccountNumber,
    openingBalance: Number(schedule.openingBalance || 0),
    additions: Number(schedule.additions || 0),
    reductions: Number(schedule.reductions || 0),
    activityExpense: Number(schedule.activityExpense || 0),
    endingBalance: Number(schedule.endingBalance || 0),
    tbEndingBalance: schedule.tbEndingBalance === null ? null : Number(schedule.tbEndingBalance),
    varianceToTB: schedule.varianceToTB === null ? null : Number(schedule.varianceToTB),
    status: schedule.status as ScheduleFormModel['status'],
    notes: schedule.notes,
    preparedBy: schedule.preparedBy ?? undefined,
    preparedAt: schedule.preparedAt ? schedule.preparedAt.toISOString() : undefined,
    reviewedBy: schedule.reviewedBy ?? undefined,
    reviewedAt: schedule.reviewedAt ? schedule.reviewedAt.toISOString() : undefined,
    lockAccount: schedule.lockAccount,
    lockPeriod: schedule.lockPeriod,
    amortMethod: schedule.amortMethod as any,
    amortStartDate: schedule.amortStartDate ? schedule.amortStartDate.toISOString().slice(0, 10) : null,
    amortEndDate: schedule.amortEndDate ? schedule.amortEndDate.toISOString().slice(0, 10) : null,
    amortMonthlyAmount: schedule.amortMonthlyAmount === null ? null : Number(schedule.amortMonthlyAmount),
    amortAutoGenerated: schedule.amortAutoGenerated,
    lines: schedule.lines.map((l) => ({
      id: l.id,
      lineType: l.lineType as any,
      lineDate: l.lineDate.toISOString().slice(0, 10),
      description: l.description,
      reference: l.reference,
      vendor: l.vendor,
      amount: Number(l.amount),
      isAutoGenerated: l.isAutoGenerated,
      generatedSource: l.generatedSource,
    })),
  }

  const readOnly = resolvedSearchParams?.mode === 'view'

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-purple-50/30">
      <div className="mx-auto max-w-5xl px-4 py-8 space-y-6">
        <Breadcrumbs
          items={[
            { label: 'Schedules', href: '/schedules' },
            { label: readOnly ? 'View' : 'Edit' },
          ]}
        />
        <ScheduleForm
          orgId={schedule.orgId}
          orgName={schedule.org?.name || null}
          periodStart={periodStart}
          periodEnd={periodEnd}
          mode="edit"
          initialSchedule={initial}
          readOnly={readOnly}
        />
      </div>
    </div>
  )
}
